import { strict as assert } from 'assert';

console.log("=== EXECUTING PHASE 2 UI CRUD MAPPING TEST ===");

const concepts = [
    { id: "uuid-A", name: "Concept A" },
    { id: "uuid-B", name: "Concept B" }
];

// Seed state (as fetched from API)
let relationships = [
    { id: "rel-1", prerequisite_concept_id: "uuid-A", target_concept_id: "uuid-B", relationship_type: "REQUIRED" }
];

const cById = new Map();
concepts.forEach(c => cById.set(c.id, c));

function getSummary(rels) {
    let req = 0; let sup = 0; let related = 0;
    rels.forEach(r => {
        const type = r.relationship_type?.toUpperCase();
        if (type === 'REQUIRED') req++;
        else if (type === 'SUPPORTING') sup++;
        else if (type === 'RELATED') related++;
    });
    return { required: req, supporting: sup, related: related };
}

try {
    // Phase 2.1: Test Summary Counter Fix
    const initialSummary = getSummary(relationships);
    assert.equal(initialSummary.required, 1, "Failed to resolve initial REQUIRED counter");
    assert.equal(initialSummary.supporting, 0, "SUPPORTING counter drifted independently");

    // Phase 2.2 Simulate Teacher Adding a new relationship via API
    const newRelationship = {
        id: "rel-2", prerequisite_concept_id: "uuid-B", target_concept_id: "uuid-A", relationship_type: "SUPPORTING"
    };

    // Simulate backend cycle logic validation
    let cycleFound = false;
    const graph = new Map();
    relationships.forEach(r => {
        if (!graph.has(r.prerequisite_concept_id)) graph.set(r.prerequisite_concept_id, []);
        graph.get(r.prerequisite_concept_id).push(r.target_concept_id);
    });
    let q = [newRelationship.target_concept_id]; // B points to A, so target is A. 
    while (q.length > 0) {
        let curr = q.shift();
        if (curr === newRelationship.prerequisite_concept_id) { cycleFound = true; break; }
        const neighbors = graph.get(curr) || [];
        for (let n of neighbors) q.push(n);
    }

    assert.equal(cycleFound, true, "Failed to detect cross-node loop topology naturally generated by adding B->A when A->B exists");

    // Simulate what would happen if we add a VALID edge (A -> C)
    const validRel = {
        id: "rel-3", prerequisite_concept_id: "uuid-A", target_concept_id: "uuid-C", relationship_type: "SUPPORTING"
    };
    relationships.push(validRel);

    const secondSummary = getSummary(relationships);
    assert.equal(secondSummary.required, 1, "Original REQUIRED logic drifted following injection.");
    assert.equal(secondSummary.supporting, 1, "Failed to increment +1 SUPPORTING relationship string count.");

    // Simulate Deletion
    relationships = relationships.filter(r => r.id !== "rel-3");
    const thirdSummary = getSummary(relationships);
    assert.equal(thirdSummary.supporting, 0, "Failed to decrement SUPPORTING edge limit identically when relationship decoupled natively.");

    console.log("PASS: Frontend TeacherPrerequisites bounds implicitly correctly map array boundaries dynamically.");
} catch (e) {
    console.error("FAIL:", e.message);
    process.exit(1);
}
